### ISSUE TITLE
Action on a highlighted item no longer opens it's respective subpage

### ISSUE THREAD

**Issue by frufru666** [xilopaint/alfred-urban-dictionary#4]
<img width="690" alt="screen shot 2019-03-07 at 12 10 37" src="https://user-images.githubusercontent.com/33035240/53952933-6b5bd100-40d2-11e9-8fd0-2c58c53afc31.png">

<img width="552" alt="screen shot 2019-03-07 at 12 12 45" src="https://user-images.githubusercontent.com/33035240/53952894-597a2e00-40d2-11e9-9dac-ac5dd13335bb.png">

**Comment by dastefster** [comment]
I just ran into this issue as well

**Comment by xilopaint** [comment]
Unfortunately, it's an API issue. There's nothing I can do about it.

**Comment by wookayin** [comment]
This is an API issue and they are lazy to fix this (I have reported the bug to the support).

I patched the `urban_dictionary.py` file on my own as follows, and it works well for me:

```diff
+        permalink = result['permalink']
+        permalink = re.sub(r'^https?://([^.]+).urbanup.com/', r'http://urbanup.com/', permalink)
         wf.add_item(valid=True,
                     title=title,
                     subtitle=result['definition'],
-                    arg=result['permalink']
+                    arg=permalink)
```

Don't forget to add `import re` at the top.

**Comment by xilopaint** [comment]
@wookayin could you explain how your patch works?

**Comment by wookayin** [comment]
It is self-explanatory, isn't it? When you check the output of the API, the permalink field would look like:

```
permalink: "http://hi.urbanup.com/7933142",
```

for the query `hi`. In general, the subhost equals the query, slugged. That's why you get a "there is no such a host" error. Instead, `http://urbanup.com/<ID>` works. So the patch simply tries to get rid of this errornous subdomain.

**Comment by xilopaint** [comment]
> It is self-explanatory, isn't it?

I'm a bit lazy with regular expressions so I just wanted you explain the substitution made by the code snippet. Now it's clear. Thank you!

Btw, have you gotten any feedback from the support? I'm undecided about either implementing the patch or waiting the fix on API side.

**Comment by wookayin** [comment]
I heard back from the UrbanDictionary support team and it appears they have fixed the issue. I can confirm that the permalink coming from the API response (i.e. with some subdomains) works very well. So we do not need to apply the patch, and I think this can be now closed.

**Comment by xilopaint** [comment]
Good to know.
